version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - "5004:5000"
    links:
      - db
  db:
    build: ./db
    volumes:
      - /vol/test/mongodb:/data/db
    ports:
      - "5005:27017"
